//
//  ATBGLEnumWrapper.cpp
//  OGLPlatform
//
//  Created by Guillaume Trollé on 31/07/2016.
//  Copyright © 2016 Guillaume Trollé. All rights reserved.
//
#include "ATBGLEnumWrapper.h"

const TwEnumVal textureParamsEV[] =
{
    { TW_TEXTURE_MODE, "TEXTURE_MODE" },
    { TW_TEXTURE_COMPARE_FUNC, "TEXTURE_COMPARE_FUNC" },
    { TW_TEXTURE_COMPARE_MODE, "TEXTURE_COMPARE_MODE" },
    { TW_TEXTURE_LOD_BIAS, "TEXTURE_LOD_BIAS" },
    { TW_TEXTURE_MIN_FILTER, "TEXTURE_MIN_FILTER" },
    { TW_TEXTURE_MAG_FILTER, "TEXTURE_MAG_FILTER" },
    { TW_TEXTURE_MIN_LOD, "TEXTURE_MIN_LOD" },
    { TW_TEXTURE_MAX_LOD, "TEXTURE_MAX_LOD" },
    { TW_TEXTURE_BASE_LEVEL, "TEXTURE_BASE_LEVEL" },
    { TW_TEXTURE_MAX_LEVEL, "TEXTURE_MAX_LEVEL" },
    { TW_TEXTURE_SWIZZLE_R, "TEXTURE_SWIZZLE_R" },
    { TW_TEXTURE_SWIZZLE_G, "TEXTURE_SWIZZLE_G" },
    { TW_TEXTURE_SWIZZLE_B, "TEXTURE_SWIZZLE_B" },
    { TW_TEXTURE_SWIZZLE_A, "TEXTURE_SWIZZLE_A" },
    { TW_TEXTURE_WRAP_S, "TEXTURE_WRAP_S" },
    { TW_TEXTURE_WRAP_T, "TEXTURE_WRAP_T" },
    { TW_TEXTURE_WRAP_R, "TEXTURE_WRAP_R" },
    { TW_TEXTURE_BORDER_COLOR, "TEXTURE_BORDER_COLOR" },
    { TW_TEXTURE_SWIZZLE_RGBA, "TEXTURE_SWIZZLE_RGBA" }
};

const TwEnumVal textureParamsValueEV[] =
{
    { TW_DEPTH_COMPONENT, "DEPTH_COMPONENT" },
    { TW_LEQUAL, "LEQUAL" },
    { TW_LESS, "LESS" },
    { TW_GREATER, "GREATER" },
    { TW_EQUAL, "EQUAL" },
    { TW_NOTEQUAL, "NOTEQUAL" },
    { TW_ALWAYS, "ALWAYS" },
    { TW_NEVER, "NEVER" },
    { TW_COMPARE_REF_TO_TEXTURE, "COMPARE_REF_TO_TEXTURE" },
    { TW_NONE, "NONE" },
    { TW_NEAREST, "NEAREST" },
    { TW_LINEAR, "LINEAR" },
    { TW_NEAREST_MIPMAP_NEAREST, "NEAREST_MIPMAP_NEAREST" },
    { TW_LINEAR_MIPMAP_NEAREST, "LINEAR_MIPMAP_NEAREST" },
    { TW_NEAREST_MIPMAP_LINEAR, "NEAREST_MIPMAP_LINEAR" },
    { TW_LINEAR_MIPMAP_LINEAR, "LINEAR_MIPMAP_LINEAR" },
    { TW_CLAMP_TO_EDGE, "CLAMP_TO_EDGE" },
    { TW_CLAMP_TO_BORDER, "CLAMP_TO_BORDER" },
    { TW_MIRRORED_REPEAT, "MIRRORED_REPEAT" },
    { TW_REPEAT ,"REPEAT" },
    { TW_MIRROR_CLAMP_TO_EDGE, "MIRROR_CLAMP_TO_EDGE" }
};

const int TEXTURE_PARAMS_COUNT = 19;
