//
//  ATBGLEnumWrapper.h
//  OGLPlatform
//
//  Created by Guillaume Trollé on 31/07/2016.
//  Copyright © 2016 Guillaume Trollé. All rights reserved.
//

#pragma once

#include <GL/glew.h>
#include <AntTweakBar.h>

enum TWTextureParams
{
    NONE = 0,
    TW_TEXTURE_MODE = GL_DEPTH_STENCIL_TEXTURE_MODE,
    TW_TEXTURE_COMPARE_FUNC = GL_TEXTURE_COMPARE_FUNC,
    TW_TEXTURE_COMPARE_MODE = GL_TEXTURE_COMPARE_MODE,
    TW_TEXTURE_LOD_BIAS = GL_TEXTURE_LOD_BIAS,
    TW_TEXTURE_MIN_FILTER = GL_TEXTURE_MIN_FILTER,
    TW_TEXTURE_MAG_FILTER = GL_TEXTURE_MAG_FILTER,
    TW_TEXTURE_MIN_LOD = GL_TEXTURE_MIN_LOD,
    TW_TEXTURE_MAX_LOD = GL_TEXTURE_MAX_LOD,
    TW_TEXTURE_BASE_LEVEL = GL_TEXTURE_BASE_LEVEL,
    TW_TEXTURE_MAX_LEVEL = GL_TEXTURE_MAX_LEVEL,
    TW_TEXTURE_SWIZZLE_R = GL_TEXTURE_SWIZZLE_R,
    TW_TEXTURE_SWIZZLE_G = GL_TEXTURE_SWIZZLE_G,
    TW_TEXTURE_SWIZZLE_B = GL_TEXTURE_SWIZZLE_B,
    TW_TEXTURE_SWIZZLE_A = GL_TEXTURE_SWIZZLE_A,
    TW_TEXTURE_WRAP_S = GL_TEXTURE_WRAP_S,
    TW_TEXTURE_WRAP_T = GL_TEXTURE_WRAP_T,
    TW_TEXTURE_WRAP_R = GL_TEXTURE_WRAP_R,
    TW_TEXTURE_BORDER_COLOR = GL_TEXTURE_BORDER_COLOR,
    TW_TEXTURE_SWIZZLE_RGBA = GL_TEXTURE_SWIZZLE_RGBA
};

enum TWTextureParamsValue
{
    TW_DEPTH_COMPONENT = GL_DEPTH_COMPONENT,
    // TW_TEXTURE_COMPARE_FUNC
    TW_LEQUAL = GL_LEQUAL,
    TW_LESS = GL_LESS,
    TW_GREATER = GL_GREATER,
    TW_EQUAL = GL_EQUAL,
    TW_NOTEQUAL = GL_NOTEQUAL,
    TW_ALWAYS = GL_ALWAYS,
    TW_NEVER = GL_NEVER,
    // TW_TEXTURE_COMPARE_MODE
    TW_COMPARE_REF_TO_TEXTURE = GL_COMPARE_REF_TO_TEXTURE,
    TW_NONE = GL_NONE,
    // TW_TEXTURE_MIN_FILTER
    TW_NEAREST = GL_NEAREST,
    TW_LINEAR = GL_LINEAR,
    TW_NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
    TW_LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
    TW_NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
    TW_LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
    // TW_TEXTURE_WRAP
    TW_CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
    TW_CLAMP_TO_BORDER = GL_CLAMP_TO_BORDER,
    TW_MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
    TW_REPEAT = GL_REPEAT,
    TW_MIRROR_CLAMP_TO_EDGE = GL_MIRROR_CLAMP_TO_EDGE
};

extern const TwEnumVal textureParamsEV[];

extern const TwEnumVal textureParamsValueEV[];

extern const int TEXTURE_PARAMS_COUNT;
/* ATBGLEnumWrapper_h */
